# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7eb9ded745935ad7dcb08c4c58c76f81e72ba01402bd1bc36d98e69d8d70ab291e5b17eced765825cbce4484e058007c4d981601dc81cdab4bc83427e14cfabc

test:
  secret_key_base: 724e54556d84ff3ad94996b80e8a7faec57e8dc8d9e79eca1ef0a987640d9a0ef969512eb4b1ba7303d16c99af4f48f95f8a815290192f75d90776beb9b280d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
